// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.2
// source: move.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MoveService_MigrateApp_FullMethodName = "/move.MoveService/MigrateApp"
)

// MoveServiceClient is the client API for MoveService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MoveServiceClient interface {
	MigrateApp(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppResponse, error)
}

type moveServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMoveServiceClient(cc grpc.ClientConnInterface) MoveServiceClient {
	return &moveServiceClient{cc}
}

func (c *moveServiceClient) MigrateApp(ctx context.Context, in *AppRequest, opts ...grpc.CallOption) (*AppResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppResponse)
	err := c.cc.Invoke(ctx, MoveService_MigrateApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MoveServiceServer is the server API for MoveService service.
// All implementations must embed UnimplementedMoveServiceServer
// for forward compatibility.
type MoveServiceServer interface {
	MigrateApp(context.Context, *AppRequest) (*AppResponse, error)
	mustEmbedUnimplementedMoveServiceServer()
}

// UnimplementedMoveServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMoveServiceServer struct{}

func (UnimplementedMoveServiceServer) MigrateApp(context.Context, *AppRequest) (*AppResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateApp not implemented")
}
func (UnimplementedMoveServiceServer) mustEmbedUnimplementedMoveServiceServer() {}
func (UnimplementedMoveServiceServer) testEmbeddedByValue()                     {}

// UnsafeMoveServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MoveServiceServer will
// result in compilation errors.
type UnsafeMoveServiceServer interface {
	mustEmbedUnimplementedMoveServiceServer()
}

func RegisterMoveServiceServer(s grpc.ServiceRegistrar, srv MoveServiceServer) {
	// If the following call pancis, it indicates UnimplementedMoveServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MoveService_ServiceDesc, srv)
}

func _MoveService_MigrateApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MoveServiceServer).MigrateApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MoveService_MigrateApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MoveServiceServer).MigrateApp(ctx, req.(*AppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MoveService_ServiceDesc is the grpc.ServiceDesc for MoveService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MoveService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "move.MoveService",
	HandlerType: (*MoveServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "MigrateApp",
			Handler:    _MoveService_MigrateApp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "move.proto",
}
